# params.yaml
base:
  random_state: 42
  image_size: [224, 224]
  batch_size: 32

model:
  learning_rate: 0.001
  num_classes: 90
  dropout_rate: 0.2

# Add to params.yaml
training:
  epochs: 1
  augmentation: True
  validation_split: 0.2