# config/config.yaml
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://drive.google.com/file/d/1Y-IwKwxptnsr-Yg-dAiPWZ1RtmdHhmZX/view?usp=share_link"  # Replace with actual Kaggle dataset path
  local_data_file: artifacts/data_ingestion/animal-images.zip
  unzip_dir: artifacts/data_ingestion/animal-images

prepare_model:
  root_dir: artifacts/prepare_model
  model_path: artifacts/prepare_model/animal_classifier_model.h5

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/animal_classifier_trained.h5

model_evaluation:
  root_dir: artifacts/model_evaluation
  metrics_file_path: artifacts/model_evaluation/metrics.csv
  confusion_matrix_path: artifacts/model_evaluation/confusion_matrix.png

prediction:
  root_dir: artifacts/prediction
  class_names_file: artifacts/prediction/class_names.json
  webapp_dir: webapp